"""
Django settings for foot_api_yolov8 project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hp9@uvc@6eww=&inb1k!a#ltx_@9q51njqm8jp-f3ryk_6fu1u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = [
    "djstripe",
    "users.apps.UsersConfig",
    "authentication.apps.AuthConfig",
    'shoefitr.apps.ShoefitrConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "crispy_forms",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    # "google_translate",
    # "storages",
    "utils",
    "models",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_app.urls'
AUTH_USER_MODEL = "shoefitr_auth.User"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",  # <-- And here
    ],
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "index"
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SAMESITE = "None"
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# try:
#     import stripe_config

#     STRIPE_LIVE_MODE = stripe_config.STRIPE_LIVE_MODE  # Boolean field

#     STRIPE_TEST_PUBLISHABLE_KEY = stripe_config.STRIPE_TEST_PUBLISHABLE_KEY
#     STRIPE_TEST_SECRET_KEY = stripe_config.STRIPE_TEST_SECRET_KEY

#     STRIPE_LIVE_PUBLISHABLE_KEY = stripe_config.STRIPE_LIVE_PUBLISHABLE_KEY
#     STRIPE_LIVE_SECRET_KEY = stripe_config.STRIPE_LIVE_SECRET_KEY
#     DJSTRIPE_WEBHOOK_SECRET = stripe_config.DJSTRIPE_WEBHOOK_SECRET

#     DJSTRIPE_FOREIGN_KEY_TO_FIELD = stripe_config.DJSTRIPE_FOREIGN_KEY_TO_FIELD

# except:
#     STRIPE_LIVE_MODE = bool(
#         strtobool(os.getenv("STRIPE_LIVE_MODE", "False"))
#     )  # Boolean field

#     STRIPE_TEST_PUBLISHABLE_KEY = os.getenv("STRIPE_TEST_PUBLISHABLE_KEY")
#     STRIPE_TEST_SECRET_KEY = os.getenv("STRIPE_TEST_SECRET_KEY")

#     STRIPE_LIVE_PUBLISHABLE_KEY = os.getenv("STRIPE_LIVE_PUBLISHABLE_KEY")
#     STRIPE_LIVE_SECRET_KEY = os.getenv("STRIPE_LIVE_SECRET_KEY")
#     DJSTRIPE_WEBHOOK_SECRET = os.getenv("DJSTRIPE_WEBHOOK_SECRET")

#     DJSTRIPE_FOREIGN_KEY_TO_FIELD = os.getenv("DJSTRIPE_FOREIGN_KEY_TO_FIELD")


STRIPE_LIVE_MODE = False  # Boolean field

STRIPE_TEST_PUBLISHABLE_KEY = "pk_test_51GsppVDTeKgTTjiSz1AapUTQWQgcAQyvfQq4NKjxrYrXv8w0ztvIaTOKCRFdwVrJA0tv93xjuGM6ChR6skbf6PA000tMN37sTN"
STRIPE_TEST_SECRET_KEY = "sk_test_51GsppVDTeKgTTjiSa1xNo0pr5AyCNG1fDah1iTzixMKOhU7q6vGfjPgwquqbhqXzeG7JU8YZI8iX4hbgVCg8q4kW002gGwDGfd"

STRIPE_LIVE_PUBLISHABLE_KEY = "pk_live_51GsppVDTeKgTTjiSV5wvqBTIoRktc6z4CKIYjpchWIi5sCqNbQCv8uMtOlbVbbHRKvetJ2kzvh3qk7VXoQOcnIL900pGSMfhpZ"
STRIPE_LIVE_SECRET_KEY = "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"

DJSTRIPE_WEBHOOK_SECRET = "whsec_Mib4XM2mu5QaTXzWisY9DNTu7W9faqnR"

DJSTRIPE_FOREIGN_KEY_TO_FIELD = "id"

LIVE_PRODUCT_ID = "prod_McgdU0l2h86H7J"

TEST_PRODUCT_ID = "prod_LBybgQ3iPGkKyk"