# Generated by Django 5.0 on 2024-03-31 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_2_8"),
        ("shoefitr_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_customers",
                to="djstripe.customer",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_subscriptions",
                to="djstripe.subscription",
            ),
        ),
    ]
